# Generated by Django 4.2.23 on 2025-07-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="description",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_time",
            new_name="placed_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="estimated_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="food_image",
        ),
        migrations.RemoveField(
            model_name="order",
            name="food_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="food_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.fooditem",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Cash on Delivery", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
