# Generated by Django 4.2.23 on 2025-07-28 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_description_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_minutes",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="orders/"),
        ),
        migrations.AddField(
            model_name="order",
            name="item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
