# Generated by Django 4.2.23 on 2025-08-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_city_profile_dob_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
