# Generated by Django 4.2.23 on 2025-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_order_gender_order_name_order_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
