# Generated by Django 4.2.23 on 2025-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
