# Generated by Django 4.2.23 on 2025-08-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_order_state_remove_profile_state_order_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="username",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
