# Generated by Django 4.2.23 on 2025-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_order_gender_alter_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
